import fnmatch
import os

headers = []
for root, dirnames, filenames in os.walk('../../../../Source'):
    headers.extend(Glob(root + '/*.hpp'))


Import('BaseEnv')

objs = []
bad_headers = ['OpenFstInterop.hpp', 'ProcedureNWAs.hpp', 'RelationOpsBuddy.hpp', 'RelationOpsPaired.hpp',
               'abbreviated-nwa.hpp']

for h in headers:
    if h.name not in bad_headers:
        cpp = BaseEnv.Command(h.name + '.cpp', [], 'echo #include \"' + h.abspath + '\" > $TARGET')
        o = BaseEnv.Object(cpp)
        objs.append(o)

Return('objs')

#print [h.abspath for h in headers]
#print h
#print dir(headers[0])


