# #############################
# Build the walidomains library

import os,platform

Debug = False

if Debug:
    print "\n+++ Build walidomains library." 


Import('WaliDir')
Import('LibInstallDir')
Import('MkStatic')
Import('BaseEnv')

walidomains_files = Split("""
./wali/domains/binrel/BinRel.cpp
""")

Env = BaseEnv.Clone()

# Define include directories
IncludeDirs = [
    os.path.join(WaliDir , 'Source'),
    os.path.join(WaliDir , 'AddOns', 'Domains' , 'Source'),
]

Env['CPPPATH'] = IncludeDirs

if MkStatic:
  walidomains = Env.StaticLibrary('walidomains' , walidomains_files)
  i = Env.Install(LibInstallDir, walidomains)
  built = [i]
  Return('built')
else:
  walidomains = Env.SharedLibrary('walidomains' , walidomains_files)
  i = Env.Install(LibInstallDir, walidomains)
  built = [i]
  Return('built')

