## ###########################################
## Delegates to:
##   (  i) ThirdParty
##   ( ii) Source
##   (iii) Examples
##
## $Id$
##
import os, os.path, sys

Import('Debug')
Import('BaseEnv')
Import('BuildDir')

if Debug:
    print '\n+++ Entered "#/AddOns/Parse"\n'

[xerces] = SConscript(os.path.join('ThirdParty','SConscript'))
built = [xerces]

[parse] = SConscript(
    os.path.join('Source','SConscript'), 
    variant_dir=os.path.join(BuildDir,'AddOns','Parse'),
    duplicate=0)
built += [parse]

examples = SConscript(os.path.join('Examples','SConscript'), 
    variant_dir=os.path.join(BuildDir,'AddOns','Parse','Examples'),
    duplicate=0)
built += examples

print 'parse = ', parse
print 'xerces= ', xerces
BaseEnv.Depends(parse,xerces)

Return('built')

