Import('BaseEnv')

built = []

xerces = SConscript('ThirdParty/SConscript')
built.append(xerces)

parse = SConscript('Source/SConscript', build_dir='_build',duplicate=0)
built.append(parse)

examples = SConscript('Examples/SConscript', build_dir='_build/Examples',duplicate=0)
built.append(examples)

BaseEnv.Alias('xerces',xerces)

BaseEnv.Depends(parse,'xerces')

Return('built')
