# #############################
# Build the waliparse library

import os,platform

## TODO : turn on debugging info output
##      - Currently broken
Debug = False

if Debug:
    print "\n+++ Build waliparse library." 


Import('WaliDir')
Import('LibInstallDir')
Import('MkStatic')
Import('BaseEnv')

if Debug:
    print "+ WaliDir       : '%s'" % WaliDir
    print "+ LibInstallDir : '%s'" % LibInstallDir 

waliparse_files = Split("""
./wali/wpds/ewpds/EWpdsHandler.cpp
./wali/wpds/WpdsHandler.cpp
./wali/wfa/WfaHandler.cpp
./wali/QueryHandler.cpp
./wali/Parser.cpp
./StrX.cpp
""")

Env = BaseEnv.Clone()

# Define include directories
IncludeDirs = [
    os.path.join(WaliDir , 'Source'),
    os.path.join(WaliDir,'AddOns','Parse','Source'),
    os.path.join(WaliDir,'AddOns','Parse','ThirdParty','xerces-c','include'),
]

if Debug:
    for i in IncludeDirs:
        print "+ Inlude        : %s" % i

Env['CPPPATH'] = IncludeDirs

if MkStatic:
    waliparse = Env.StaticLibrary('waliparse' , waliparse_files)
    i = Env.Install(LibInstallDir, waliparse)
    built = [i]
    Return('built')
else:
    waliparse = Env.SharedLibrary('waliparse' , waliparse_files)
    i = Env.Install(LibInstallDir, waliparse)
    built = [i]
    Return('built')

