# Build the library

Import('WaliDir')


Import('LibInstallDir')

waliparse_files = Split("""
./wali/wpds/ewpds/EWpdsHandler.cpp
./wali/wpds/ewpds/MergeFactory.cpp
./wali/wpds/WpdsHandler.cpp
./wali/wfa/WfaHandler.cpp
./wali/QueryHandler.cpp
./wali/Parser.cpp
./StrX.cpp
""")

env = Environment(
    CPPPATH  = [
      WaliDir + '/Source',
      WaliDir + '/AddOns/Parse/Source',
      WaliDir + '/AddOns/Parse/ThirdParty/xerces-c/include',
    ],
    CXXFLAGS = '-g -ggdb -Wall -Wformat=2 -W'
)

waliparse = env.SharedLibrary('waliparse' , waliparse_files)

env.Install(LibInstallDir, waliparse)

