# Build the test programs 
import os,os.path

Import('WaliDir')
Import('LibInstallDir')
Import('ProgEnv')
Import('Debug')

if Debug:
    print '\n+++ Entered "#/Tests/SConscript"\n'

## ###############################
## Environment
## Adding Domains paths to the enviornment

Env = ProgEnv.Clone()

## Note - Be sure to use a list when 'Append'ing to CPPPATH
Env.Append(CPPPATH = [os.path.join(WaliDir,'Examples','Reach')])

TestDir = os.path.join(WaliDir,'Tests')

built = []

Reach = os.path.join(WaliDir,'Examples','Reach','Reach.cpp')
for t in ['t1','t3','t4','twitness','tprune','tTransSet']:
    exe = Env.Program('%s' % t, ['%s.cpp' % t,'%s' % Reach ])
    built += Env.Install('#/Tests/harness',exe)

Return('built')

