# Build the test programs 
import os,os.path

Import('WaliDir')
Import('LibInstallDir')
Import('ProgEnv')

## ###############################
## Environment
Env = ProgEnv.Clone()
Env['CPPPATH']  += [os.path.join(WaliDir,'Examples','Reach')]
 
TestDir = os.path.join(WaliDir,'Tests')

built = []

Reach = os.path.join(WaliDir,'Examples','Reach','Reach.cpp')
for t in ['t1','t3','t4','twitness','tprune','tTransSet']:
    print '\n+++ Building Test "%s"' % t
    exe = Env.Program('%s' % t, ['%s.cpp' % t,'%s' % Reach ] + Env['StaticLibs'])
    built.append(exe)

Return('built')

