## ##################################
## Build libdomains
## $Id: SConscript 1610 2012-01-30 23:30:19Z driscoll $
import os,os.path

Import('Debug')
Import('BaseEnv')
Import('BuildDir')

if Debug:
    print '\n+++ Entered "#/AddOns/Domains/SConscript"\n'
    
built = []

buddy = SConscript('ThirdParty/SConscript')
built += buddy

domains = SConscript(
    'Source/SConscript', 
    variant_dir=os.path.join(BuildDir,'AddOns','Domains'),
    duplicate=0)

built += domains

BaseEnv.Depends(domains,buddy)

Return('built')

