Import('BaseEnv')

built = []

buddy = SConscript('ThirdParty/SConscript')
built += buddy

domains = SConscript('Source/SConscript', build_dir='_build',duplicate=0)
built += domains

BaseEnv.Depends(domains,buddy)

Return('built')

