#include "wali/nwa/construct/complement.hpp"
#include "wali/nwa/construct/concat.hpp"
#include "wali/nwa/construct/determinize.hpp"
#include "wali/nwa/construct/intersect.hpp"
#include "wali/nwa/construct/reverse.hpp"
#include "wali/nwa/construct/star.hpp"
#include "wali/nwa/construct/union.hpp"
