#!/bin/bash

cd $(dirname "$0")

WALI=../../../..

DEV_NULL=/dev/null

if [ $(uname -o) = "Cygwin" ]
then
    DEV_NULL=NUL
fi

for BZ2 in *.bz2; do
    ROOT=$(basename "$BZ2" .bz2)
    if [ ! -e "$ROOT" ]; then
        bunzip2 --keep "$BZ2"
    fi

    echo "*********************************"
    echo "Test: $ROOT"
    time $WALI/bin64/nwa-get-example.exe "$ROOT" > $DEV_NULL
    echo
    echo
done


