# Build the example applications
import os

Import('WaliDir')
Import('LibInstallDir')
Import('BaseEnv')

## ###############################
## Environment
Env = BaseEnv.Clone()
 
## Libraries
Libs = [ 'wali', ]
Env['LIBS'] = Libs
 
## Library search path
LibDirs = [ LibInstallDir ]
Env['LIBPATH'] = LibDirs

Export('Env')

ExampleDir = os.path.join(WaliDir,'Examples')

built = []
## ###############################
## Reach example
o = SConscript(
        os.path.join(ExampleDir,'Reach','SConscript'),
        build_dir= os.path.join('_build','Reach'),
        duplicate=0
        )
built += o


## ###############################
## GenKill examples
o = SConscript(
        os.path.join(ExampleDir,'GenKill','SConscript'),
        build_dir= os.path.join('_build','GenKill'),
        duplicate=0
        )
built += o

# Affine Relations Weight Domain
# o = SConscript(
#         os.path.join(ExampleDir,'AffineRelations','SConscript'),
#         build_dir= os.path.join('_build','AffineRelations'),
#         duplicate=0
#         )
# built += o
Return('built')
