# Build the example applications
import os,os.path

Import('Debug')
Import('WaliDir')
Import('BuildDir')

if Debug:
    print '\n+++ Entered "#/Examples/SConscript"\n'
    
ExampleDir = os.path.join(WaliDir,'Examples')

built = []
## ###############################
## Reach example
built += SConscript(
        os.path.join(ExampleDir,'Reach','SConscript'),
        variant_dir= os.path.join(BuildDir,'Examples','Reach'),
        duplicate=0
        )


## ###############################
## GenKill examples
built += SConscript(
        os.path.join(ExampleDir,'GenKill','SConscript'),
        variant_dir= os.path.join(BuildDir,'Examples','GenKill'),
        duplicate=0
        )

built += SConscript(
        os.path.join(ExampleDir,'ProgAnalysis','SConscript'),
        variant_dir= os.path.join(BuildDir,'Examples','ProgAnalysis'),
        duplicate=0)

# Affine Relations Weight Domain
# o = SConscript(
#         os.path.join(ExampleDir,'AffineRelations','SConscript'),
#         variant_dir= os.path.join('_build','AffineRelations'),
#         duplicate=0
#         )
# built += o

Return('built')

