# Reachability example
import os

Import('WaliDir')
Import('ProgEnv')

ReachFiles=Split("""
    Reach.cpp
    ExReach.cpp
""")

ExReach = ProgEnv.Program('ExReach',ReachFiles + ProgEnv['StaticLibs'])

built = [ProgEnv.Install(os.path.join(WaliDir,'Examples','bin'), ExReach)]

ExReachWit = ProgEnv.Program(
    'ExReachWit',['Reach.cpp','ExReachWit.cpp']+ProgEnv['StaticLibs'])
built += [ProgEnv.Install(os.path.join(WaliDir,'Examples','bin'), ExReachWit)]

Return('built')

