# Reachability example
import os

Import('WaliDir')
Import('ProgEnv')

ReachFiles=Split("""
    Reach.cpp
    ExReach.cpp
""")

ExReach = ProgEnv.Program('ExReach',ReachFiles + ProgEnv['StaticLibs'])

i = ProgEnv.Install(os.path.join(WaliDir,'Examples','bin'), ExReach)

built = [i]

Return('built')

