# #############################
# Build the waliparse library

import os,platform

Import('Debug')
Import('WaliDir')
Import('BinInstallDir')
Import('ProgEnv')

if Debug:
    print '\n+++ Entered "#/AddOns/RandomNwa/Source/SConscript"\n'

files = Split("""
    main.cpp
""")

Env = ProgEnv.Clone()

Env['WARNING_FLAGS'] = Env['WARNING_FLAGS'].replace('-Wshadow', '')

#Env.Append(CPPPATH=[os.path.join(WaliDir,'AddOns','RandomNwa','Source')])
Env.Append(LIBS=['boost_program_options'])

built = Env.Program('random-nwa', files)

built += Env.Install(BinInstallDir, built)

Return('built')
