# #############################
# Build the waliparse library

import os,platform

Import('Debug')
Import('WaliDir')
Import('BinInstallDir')
Import('ProgEnv')

if Debug:
    print '\n+++ Entered "#/AddOns/RandomNwa/Source/SConscript"\n'

files = Split("""
    main.cpp
""")

Env = ProgEnv.Clone()

Env.Append(CCFLAGS='-O0')

Env['WARNING_FLAGS'] = Env['WARNING_FLAGS'].replace('-Wshadow', '')
Env['WARNING_FLAGS'] = Env['WARNING_FLAGS'].replace('-Wfloat-equal', '')

#Env.Append(CPPPATH=[os.path.join(WaliDir,'AddOns','RandomNwa','Source')])
Env.Append(CPPPATH=['/unsup/boost-1.47.0/include'])
Env.Append(LIBPATH=['/unsup/boost-1.47.0/lib'])
Env.Append(RPATH=['/unsup/boost-1.47.0/lib'])
Env.Append(LIBS=['boost_program_options'])

built = Env.Program('random-nwa', files)

built += Env.Install(BinInstallDir, built)

Return('built')
