/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_wali_WRAP_H_
#define SWIG_wali_WRAP_H_

#include <map>
#include <string>


class SwigDirector_PySemElem : public PySemElem, public Swig::Director {

public:
    SwigDirector_PySemElem(PyObject *self);
    virtual ~SwigDirector_PySemElem();
    virtual bool underApproximates(wali::SemElem *that);
    virtual std::ostream &marshall(std::ostream &o) const;
    virtual wali::sem_elem_t diff(wali::SemElem *se);
    virtual wali::sem_elem_t star();
    virtual wali::sem_elem_t extendAndDiff(wali::sem_elem_t next, wali::sem_elem_t subtrahend);
    virtual bool containerLessThan(wali::SemElem const *other) const;
    virtual size_t hash() const;
    virtual std::ostream &print_typename(std::ostream &os) const;
    virtual std::string __str__() const;
    virtual wali::ref_ptr< PySemElem > pycombine(PySemElem *se) const;
    virtual wali::ref_ptr< PySemElem > pyextend(PySemElem *se) const;
    virtual std::pair< wali::ref_ptr< PySemElem >,wali::ref_ptr< PySemElem > > pydelta(PySemElem *se);
    virtual bool pyequal(PySemElem *se) const;
    virtual wali::ref_ptr< PySemElem > pyone() const;
    virtual wali::ref_ptr< PySemElem > pyzero() const;

/* Internal director utilities */
public:
    bool swig_get_inner(const char *swig_protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(swig_protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }
    void swig_set_inner(const char *swig_protected_method_name, bool val) const {
      swig_inner[swig_protected_method_name] = val;
    }
private:
    mutable std::map<std::string, bool> swig_inner;

#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
/* VTable implementation */
    PyObject *swig_get_method(size_t method_index, const char *method_name) const {
      PyObject *method = vtable[method_index];
      if (!method) {
        swig::SwigVar_PyObject name = SWIG_Python_str_FromChar(method_name);
        method = PyObject_GetAttr(swig_get_self(), name);
        if (!method) {
          std::string msg = "Method in class PySemElem doesn't exist, undefined ";
          msg += method_name;
          Swig::DirectorMethodException::raise(msg.c_str());
        }
        vtable[method_index] = method;
      }
      return method;
    }
private:
    mutable swig::SwigVar_PyObject vtable[14];
#endif

};


#endif
