import os, os.path, sys

Import('Debug')
Import('BaseEnv')
Import('BuildDir')
Import('ProgEnv')

if Debug:
    print '\n+++ Entered "#/AddOns/RandomFWPDS"\n'

#compile_files = """
#Source/generateRandomFWPDS.cpp
#"""

built = []
#built += ProgEnv.Object('generateRandomFWPDS', Split(compile_files)) 
Return('built')

